# 应用进程和容器配置文件
# 格式: 类型:名称/容器名
# 类型: process, docker

# ========== 虚拟机/物理机部署的服务和进程 ==========
# 格式: process:进程名:服务名
process:sshd:SSH服务
process:cron:定时任务服务
process:nginx:Web服务器

# ========== 容器部署的应用 ==========
# 格式: docker:容器名:服务名
#docker:kafka:消息队列
#docker:mysql:数据库
