# 服务器配置文件
# 格式: 别名:IP:端口:用户:密钥(可空):密码(可空):组标签
# 示例:
devserv:192.168.0.1:22:traesolo:/home/traesolo/patrol/.autopriv/patrol_rsa::group_host2
prodserv:192.168.0.2:22:traesolo:/home/traesolo/patrol/.autopriv/patrol_rsa::group_host_all
testserv:192.168.0.100:22:traesolo:/home/traesolo/patrol/.autopriv/patrol_rsa::group_all
